online_booking_system/booking/urls.py
# -*- coding:utf-8 -*-  
'''
@author: Zhao Liyong 
@license: NA
@contact: 3100102825@zju.edu.cn 
@see: NA
 
@version: 0.9.5 
@todo[1.0.0]: css and some form 


this code show how the url is processed
'''  
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                    url(r'^$','booking.views.index'),
                    
                    url(r'^flight/$','booking.views.search_flight'),
                    url(r'^hotel/$','booking.views.search_hotel'),
                    
                    url(r'^flight/(?P<pk_id>\d+)/$','booking.views.book_flight'),
                    url(r'^hotel/(?P<pk_id>\d+)/$','booking.views.book_hotel'),
                    url(r'^my_record/flight/$','booking.views.my_flight_record'),
                    url(r'^my_record/hotel/$','booking.views.my_hotel_record'),
                    url(r'^my_record/flight/(?P<pk_id>\d+)/$','booking.views.flight_record_view'),
                    url(r'^my_record/hotel/(?P<pk_id>\d+)/$','booking.views.hotel_record_view'),
)

online_booking_system/online_booking_system/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'online_booking_system.views.home', name='home'),
    # url(r'^online_booking_system/', include('online_booking_system.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$','booking.views.index'),
    
    
    url(r'^sys/',include('adminInfo.urls')),
    
    url(r'^booking/',include('booking.urls')),
    
    url(r'^accounts/login/$','userInfo.views.login_view'),
    
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login'}),
    url(r'^accounts/reg/$','userInfo.views.register'),
)

online_booking_system/booking/models.py
# -*- coding:utf-8 -*-  
'''
@author: Zhao Liyong 
@license: NA
@contact: 3100102825@zju.edu.cn 
@see: NA
 
@version: 0.9.5 
@todo[1.0.0]: css and some form 


this code show how the data is stored in the database
'''  
from django.db import models

from django.contrib.auth.models import User #我们小组不负责用户和管理员的注册和登录验证，所以为了方便测试，我们使用了django自带的验证工具
class city(models.Model):#这是城市的表 可以添加更多数据 加强功能
    '''
    @note this is the city object.
    '''
    pinyin = models.CharField(max_length=5, unique=True)
    name = models.CharField(max_length=256, unique=True)
    
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return self.name
class company(models.Model):
    '''
    @note this is the company object.
    '''
    name = models.CharField(max_length=256, unique=True)
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return self.name
FLIGHT_CHOICES = (
        ('1','economy'),
        ('2','business'),
        ('3','first class'),
    )
class flight(models.Model):
    '''
    @note this is the flight infomation object.
    '''
    starting_id  = models.ForeignKey(city,related_name='+',verbose_name ="出发地点");#models.CharField(max_length=4, choices=CITY_CHOICE,verbose_name ="出发城市")
    destination_id = models.ForeignKey(city,related_name='+',verbose_name ="目的地"); #models.CharField(max_length=4, choices=CITY_CHOICE,verbose_name ="到达城市")
    company_id = models.ForeignKey(company,related_name='+',verbose_name ="航空公司")
    
    none_stop = models.BooleanField(verbose_name ="直飞")

    plane_type = models.CharField(max_length=1, choices=FLIGHT_CHOICES,verbose_name ="舱位等级")
    
    price = models.FloatField(verbose_name ="价格")
    leave_date = models.DateField(verbose_name ="出发日期")
    leave_time = models.TimeField(verbose_name ="出发时间")
    arrive_date = models.DateField(verbose_name ="到达日期")
    arrive_time = models.TimeField(verbose_name ="到达时间")
    leave_number = models.IntegerField(verbose_name ="剩余票数")
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        f_type = FLIGHT_CHOICES[int(self.plane_type)-1][1]
        return u'{} {}->{} {} {} {}->{} {} {}:￥{} {}个座位'\
            .format(self.company_id, self.starting_id,self.destination_id,u'直飞' if self.none_stop else u'中转',self.leave_date,\
            self.leave_time,self.arrive_date,self.arrive_time,f_type,self.price,self.leave_number)


    
STAR_CHOICES = (
        ('2','<=2 stars'),
        ('3', '3 stars'),
        ('4', '4 stars'),
        ('5','5 stars'),
    )
ROOM_CHOICES = (
        ('1', 'standard'),
        ('2', 'big'),
    )
class hotel(models.Model):
    '''
    @note this is the hotel infomation object.
    '''
    name = models.CharField(max_length=256)

    hotel_star = models.CharField(max_length=1, choices=STAR_CHOICES)
    img_url = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    phone_number = models.CharField(max_length=16)
    city_id = models.ForeignKey(city,related_name='+')
    
    price = models.FloatField()

    room_type = models.CharField(max_length=1, choices=ROOM_CHOICES)
    hot_level = models.IntegerField(default=0)
    commented_num = models.IntegerField(default=0)
    scores = models.IntegerField(default=-1)
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        r_type = ROOM_CHOICES[int(self.room_type)-1][1]
        h_type = STAR_CHOICES[int(self.hotel_star)-2][1]
        return u'{} {} {} {} {}: ￥{} 热度:{} 评分:{}' \
            .format(self.city_id, self.name,h_type,self.phone_number,r_type,self.price,self.hot_level,'not comented yet!' if self.scores==-1 else str(self.scores))

class room_num(models.Model):
    '''
    @note this is the hotel room infomation object.
    '''
    hotel_id = models.ForeignKey(hotel,related_name='+')
    room_number = models.IntegerField()
    date = models.DateField()
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return u'{} {} 剩余{}个房间' .format(self.hotel_id,self.date,self.room_number)
class flight_discount(models.Model):
    '''
    @note this is the flight discount infomation object.
    '''
    flight_id  = models.ForeignKey(flight,related_name='+')
    discount = models.FloatField()
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return u'{}-{}' .format(self.flight_id,self.discount)
class room_discount(models.Model):
    '''
    @note this is the room discount infomation object.
    '''
    hotel_id  = models.ForeignKey(hotel,related_name='+')
    discount = models.FloatField()
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return u'{}-{}' .format(self.hotel_id,self.discount)
class hotel_record(models.Model):
    '''
    @note this is the hotel room booking record infomation object.
    '''
    user_id = models.ForeignKey(User,related_name='+')
    hotel_id = models.ForeignKey(hotel,related_name='+')
    comment = models.CharField(max_length=512,default='')
    scores = models.IntegerField(default=-1)
    checkin_date = models.DateField()
    last = models.IntegerField()
    num = models.IntegerField()
    book_date = models.DateField()
    book_time = models.TimeField()
    price = models.IntegerField()
    #"0" unpayed
    #"1" payed
    stat = models.CharField(max_length=1)
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return u'{}-{}' .format(self.user_id,self.hotel_id)
class flight_record(models.Model):
    '''
    @note this is the hotel flight booking record infomation object.
    '''
    user_id = models.ForeignKey(User,related_name='+')
    flight_id = models.ForeignKey(flight,related_name='+')

    comment = models.CharField(max_length=512,default='')
    scores = models.IntegerField(default=-1)
    num = models.IntegerField()
    book_date = models.DateField()
    book_time = models.TimeField()
    price = models.IntegerField()
    #"0" unpayed
    #"1" payed
    stat = models.CharField(max_length=1)
    def __unicode__(self):
        '''
        @return: returns how the object will be printed
        '''
        return u'{}-{}' .format(self.user_id,self.flight_id)

online_booking_system/booking/forms.py
# -*- coding:utf-8 -*-  
from django import forms
import datetime
from booking.data import COMPANY_CHOICES
#这是航班搜索的表单
class flightForm(forms.Form):
    start = forms.CharField(label='start city',initial='阿克苏')
    des = forms.CharField(label='destination city',initial='安庆')
    date = forms.DateField(label='leave date',initial=datetime.date(2013, 6, 1))
    company = forms.ChoiceField(label='company',choices=COMPANY_CHOICES)
    NoneStop=(
              ('0','unlimit'),
              ('1','true'),
              ('2','false'),
              )
    non_stop = forms.ChoiceField(label='nonstop',choices=NoneStop)
    FLIGHT_CHOICES = (
        ('0','unlimit'),
        ('1','economy'),
        ('2','business'),
        ('3','first class'),
    )
    level = forms.ChoiceField(label='class',choices=FLIGHT_CHOICES)
    I_or_D_CHOICES = (
                      ('0',u'unsort'),
                      ('1',u'increase'),
                      ('2',u'decrease'),
                      )
                      
    I_or_D = forms.ChoiceField(label='how to sort',choices=I_or_D_CHOICES)
    SORT_BY = (
               ('0','unsort'),
               ('price','price'),
               ('company_id','company'),
               ('none_stop','none_stop'),
               ('leave_time','leave_time'),
               )
    sort_by = forms.ChoiceField(label='sort by',choices=SORT_BY)
#这是酒店搜索的表单
class hotelForm(forms.Form):
    city = forms.CharField(label='city',initial='北京')
    start = forms.DateField(label='check in date',initial=datetime.date(2013, 6, 1))
    last = forms.IntegerField(label='days to live in',initial=1)
    STAR_CHOICES = (
        ('0', 'unlimit'),
        ('2','<=2 stars'),
        ('3', '3 stars'),
        ('4', '4 stars'),
        ('5','5 stars'),
    )
    star = forms.ChoiceField(label='star level',choices=STAR_CHOICES)
    ROOM_CHOICES = (
        ('0', 'unlimit'),
        ('1', 'standard'),
        ('2', 'big'),
    )
    room_type =forms.ChoiceField(label='room type',choices=ROOM_CHOICES)
    keyword = forms.CharField(label='keyword',required=False)#keyword可以不填
    I_or_D_CHOICES = (
                      ('0',u'unsort'),
                      ('1',u'increase'),
                      ('2',u'decrease'),
                      )
                      
    I_or_D = forms.ChoiceField(label='how to sort',choices=I_or_D_CHOICES)
    SORT_BY = (
               ('0','unsort'),
               ('price','price'),
               ('hotel_star','hotel star'),
               ('scores','scores'),
               ('hot_level','hot level'),
               )
    sort_by = forms.ChoiceField(label='sort by',choices=SORT_BY)
        
        

online_booking_system/booking/templates/fr_detail.html
{% extends "base.html" %}
{% block title %}your flight record detail{% endblock %}

{% block content %}
<div class="span2">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">
				Search
			</li>
			<li>
				<a href="/booking/hotel/">search hotel</a>
			</li>
			<li>
				<a href="/booking/flight/">search flight</a>
			</li>
			<li class="nav-header">
				your records
			</li>
			<li>
				<a href="/booking/my_record/flight/">your flight records</a>
			</li>
			<li>
				<a href="/booking/my_record/hotel/">your hotel records</a>
			</li>
			<li class="nav-header">
				admin options
			</li>
			<li>
				<a href="/sys/city/">manage cities</a>
			</li>
			<li>
				<a href="/sys/company/">manage comanys</a>
			</li>
		</ul>
	</div><!--/.well -->
</div><!--/span-->
<div class="span10">

	<div class="hero-unit">
		<p>make comment on{{fr}}</p>
	</div>
	<div class="row-fluid">
		<div class="well span12">

			<form enctype="multipart/form-data" action="" method="post" id="r_form">
				{% csrf_token %}
				<table class="table table-bordered">
					<p>
						<label class="required">make score:</label>

						<input name="score" type="number" />
					</p>
					<p>
						<label  class="required">make comment:</label>
						<textarea rows="10" cols="30" name="comment" ></textarea>
					</p>
					<input type="submit" value="submit" class="default" name="save" />

				</table>
			</form>
			</div>
		</div><!--/span-->
	</div><!--/row-->

</div>
{% endblock %}

online_booking_system/booking/templates/search_flight.html
{% extends "base.html" %}
{% block title %}
online booking system
{% endblock %}
{% block css %}
<link type="text/css" rel="stylesheet" href="/static/css/demos.css"/>
<link type="text/css" rel="stylesheet" href="/static/css/themes/base/jquery.ui.all.css"/>
<link type="text/css" rel="stylesheet" href="/static/css/jock-citypicker-2.0.css" />
{% endblock %}
{% block content %}
<div class="span2">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">
				Search
			</li>
			<li>
				<a href="/booking/hotel/">search hotel</a>
			</li>
			<li>
				<a href="/booking/flight/">search flight</a>
			</li>
			<li class="nav-header">
				your records
			</li>
			<li>
				<a href="/booking/my_record/flight/">your flight records</a>
			</li>
			<li>
				<a href="/booking/my_record/hotel/">your hotel records</a>
			</li>
			<li class="nav-header">
				admin options
			</li>
			<li>
				<a href="/sys/city/">manage cities</a>
			</li>
			<li>
				<a href="/sys/company/">manage comanys</a>
			</li>
		</ul>
	</div><!--/.well -->
</div><!--/span-->
<div class="span9">

	<div class="row-fluid">
		<div class="well row-fluid">
			<form action="" method="post" >
				{% csrf_token %}

				<div class="span3">
					<label for="id_start">start city:</label>
					<input id="id_start" name="start" type="text" value="阿克苏" />

					<label for="id_des">destination city:</label>
					<input id="id_des" name="des" type="text" value="安庆" />

					<label for="id_date">leave date:</label>
					<input id="id_date" name="date" type="text" value="2013-06-01" />
				</div>
				<div class="span3">
					<label for="id_company">company:</label>
					<select id="id_company" name="company">
						<option value="0">unlimit</option>
						<option value="1">中国国航</option>
						<option value="2">南方航空</option>
						<option value="3">东方航空</option>
						<option value="4">海南航空</option>
						<option value="5">深圳航空</option>
						<option value="6">厦门航空</option>
						<option value="7">四川航空</option>
						<option value="8">上海航空</option>
						<option value="9">山东航空</option>
						<option value="10">吉祥航空</option>
						<option value="11">中联航</option>
						<option value="12">首都航空</option>
						<option value="13">天津航空</option>
						<option value="14">云南祥鹏</option>
						<option value="15">奥凯航空</option>
						<option value="16">成都航空</option>
						<option value="17">西部航空</option>
						<option value="18">大新华</option>
						<option value="19">昆明航空</option>
						<option value="20">河北航空</option>
						<option value="21">西藏航空</option>
						<option value="22">华夏航空</option>
						<option value="23">幸福航空</option>
						<option value="24">河南航空</option>
					</select>

					<label for="id_non_stop">nonstop:</label>
					<select id="id_non_stop" name="non_stop">
						<option value="0">unlimit</option>
						<option value="1">true</option>
						<option value="2">false</option>
					</select>

					<label for="id_level">class:</label>
					<select id="id_level" name="level">
						<option value="0">unlimit</option>
						<option value="1">economy</option>
						<option value="2">business</option>
						<option value="3">first class</option>
					</select>
				</div>
				<div class="span3">
					<label for="id_I_or_D">how to sort:</label>
					<select id="id_I_or_D" name="I_or_D">
						<option value="0">unsort</option>
						<option value="1">increase</option>
						<option value="2">decrease</option>
					</select>

					<label for="id_sort_by">sort by:</label>
					<select id="id_sort_by" name="sort_by">
						<option value="0">unsort</option>
						<option value="price">price</option>
						<option value="company_id">company</option>
						<option value="none_stop">none_stop</option>
						<option value="leave_time">leave_time</option>
					</select>
					<label>&nbsp;</label>
					<input type="submit" class="btn" value="Submit">
				</div>

			</form>
		</div>
		<div class="well row-fluid">
			<h1>query result</h1>
			<table class="table-bordered table table-striped">
				<thead>
					<tr class="row">
						<th>#</th>
						<th>start city</th>
						<th>destination city</th>
						<th>take off date</th>
						<th>take off time</th>
						<th>arrive date</th>
						<th>arrive time</th>
						<th>comany</th>
						<th>nonestop</th>
						<th>plane class</th>
						<th>price</th>
						<th>opration</th>
					</tr>
				</thead>
				<tbody>
					{%for s in rs%}

					<tr class="row">
						<td>{{s.id}}</td>
						<td>{{s.starting_id}}</td>
						<td>{{s.destination_id}}</td>
						<td>{{s.leave_date}}</td>
						<td>{{s.leave_time}}</td>
						<td>{{s.arrive_date}}</td>
						<td>{{s.arrive_time}}</td>
						<td>{{s.company_id}}</td>
						<td>{{s.none_stop}}</td>
						<td> {%ifequal s.plane_type '1'%}
						economy
						{%else%}

						{%ifequal s.plane_type '2'%}
						business
						{%else%}
						first class
						{%endifequal%}
						{%endifequal%} </td>
						<td>{{s.price}}</td>
						<td><a href="/booking/flight/{{s.pk}}/" class="btn"> book</a></td>
					</tr>

					{% endfor %}
				</tbody>

			</table>

			<div class="pagination">
				<ul>
					{% if rs.has_previous %}
					<li>
						<a href="?p={{ rs.previous_page_number }}">previous</a>
					</li>
					{% endif %}
					<li class="active">
						<a>Page {{ rs.number }} of {{ rs.paginator.num_pages }}.</a>
					</li>
					{% if rs.has_next %}
					<li>
						<a href="?p={{ rs.next_page_number }}">next</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}

<script type="text/javascript" src="/static/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.datepicker.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.position.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.tooltip.js"></script>
<script type="text/javascript" src="/static/js/jock-citypicker-2.0.js"></script>

<script type="text/javascript">
	$(function() {

		$("#id_date").datepicker({
			dateFormat : 'yy-mm-dd'
		});

		var c = document.getElementById("id_start");

		var fn1 = function(city) {
			c.value = city;
		};
		c.onclick = function() {
			citypicker.show({
				left : 300,
				top : 300,
				selected : fn1
			});
		};

		var d = document.getElementById("id_des");

		var fn2 = function(city) {
			d.value = city;
		};
		d.onclick = function() {
			citypicker.show({
				left : 300,
				top : 350,
				selected : fn2
			});
		};

		function hide_this() {
			if ($("#id_I_or_D").children('option:selected').val() == '0') {
				$("#id_sort_by").val(0);
				$("#id_sort_by").attr("hidden", true);
				$("[for ='id_sort_by']").attr('hidden', true);
			} else {
				$("#id_sort_by").attr("hidden", false);
				$("[for ='id_sort_by']").attr('hidden', false);
			}
		}

		hide_this();
		$("#id_I_or_D").change(function() {
			hide_this();
		});
	}); 
</script>
{% endblock %}

online_booking_system/booking/templates/search_hotel.html
{% extends "base.html" %}
{% block title %}
online booking system
{% endblock %}
{% block css %}
<link type="text/css" rel="stylesheet" href="/static/css/demos.css"/>
<link type="text/css" rel="stylesheet" href="/static/css/themes/base/jquery.ui.all.css"/>
<link type="text/css" rel="stylesheet" href="/static/css/jock-citypicker-2.0.css" />
{% endblock %}
{% block content %}
<div class="span2">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">
				Search
			</li>
			<li>
				<a href="/booking/hotel/">search hotel</a>
			</li>
			<li>
				<a href="/booking/flight/">search flight</a>
			</li>
			<li class="nav-header">
				your records
			</li>
			<li>
				<a href="/booking/my_record/flight/">your flight records</a>
			</li>
			<li>
				<a href="/booking/my_record/hotel/">your hotel records</a>
			</li>
			<li class="nav-header">
				admin options
			</li>
			<li>
				<a href="/sys/city/">manage cities</a>
			</li>
			<li>
				<a href="/sys/company/">manage comanys</a>
			</li>
		</ul>
	</div><!--/.well -->
</div><!--/span-->
<div class="span9">

	<div class="row-fluid">
		<div class="well row-fluid">
			<form action="" method="post" >
				{% csrf_token %}
				<div class="span3">
					<label for="id_city">city:</label>
					<input id="id_city" name="city" type="text" value="北京" />

					<label for="id_start">check in date:</label>
					<input id="id_start" name="start" type="text" value="2013-06-01" />

					<label for="id_last">days to live in:</label>
					<input id="id_last" name="last" type="text" value="1" />
				</div>
				<div class="span3">
					<label for="id_star">star level:</label>
					<select id="id_star" name="star">
						<option value="0" selected="selected">unlimit</option>
						<option value="2">&lt;=2 stars</option>
						<option value="3">3 stars</option>
						<option value="4">4 stars</option>
						<option value="5">5 stars</option>
					</select>

					<label for="id_room_type">room type:</label>
					<select id="id_room_type" name="room_type">
						<option value="0" selected="selected">unlimit</option>
						<option value="1">standard</option>
						<option value="2">big</option>
					</select>

					<label for="id_keyword">keyword:</label>
					<input id="id_keyword" name="keyword" type="text" />
				</div>
				<div class="span3">
					<label for="id_I_or_D">how to sort:</label>
					<select id="id_I_or_D" name="I_or_D">
						<option value="0" selected="selected">unsort</option>
						<option value="1">increase</option>
						<option value="2">decrease</option>
					</select>

					<label for="id_sort_by">sort by:</label>
					<select id="id_sort_by" name="sort_by">
						<option value="0" selected="selected">unsort</option>
						<option value="price">price</option>
						<option value="hotel_star">hotel star</option>
						<option value="scores">scores</option>
						<option value="hot_level">hot level</option>
					</select>
					<label>&nbsp;</label>
					<input type="submit" class="btn" value="Submit">
				</div>
			</form>

		</div>
		<div class="well row-fluid">
			<h1>query result</h1>
			
			
			{% for rr in rs%}
			<div class="well">
				<div class=" row-fluid">
					<div class="span4">
						<img src="/{{rr.img_url}}">
					</div>
					<div class="span4">
						<dl class="dl-horizontal">
							<dt>
								name
							</dt>
							<dd>
								{{rr.name}}
							</dd>

							<dt>
								city
							</dt>
							<dd>
								{{rr.city_id}}
							</dd>
							<dt>
								address
							</dt>
							<dd>
								{{rr.address}}
							</dd>

							<dt>
								phone number
							</dt>
							<dd>
								{{rr.phone_number}}
							</dd>
							<dt>
								room type
							</dt>
							<dd>
								{%ifequal rr.room_type 1%}
								standard
								{%else%}

								big
								{%endifequal%}
							</dd>
						</dl>
					</div>
					<div class="span4">

						<dl class="dl-horizontal">
							<dt>
								hotel star
							</dt>
							<dd>
								{{rr.hotel_star}} stars
							</dd>

							<dt>
								hot level
							</dt>
							<dd>
								{{rr.hot_level}}
							</dd>
							<dt>
								scores
							</dt>
							<dd>
								{%ifequal  rr.scores -1 %}
								no one comment
								{%else%}
								{{rr.scores}}
								{%endifequal %}
							</dd>

							
							<dt>
								price
							</dt>
							<dd>
								{{rr.price}}
							</dd>
						</dl>
						
					</div>
					<a class="btn" href="/booking/hotel/{{rr.id}}/">Go to Book this</a>
				</div>

			</div>
			{% endfor %}
			

			<div class="pagination">
				<ul>
					{% if rs.has_previous %}
					<li>
						<a href="?p={{ rs.previous_page_number }}">previous</a>
					</li>
					{% endif %}
					<li class="active">
						<a>Page {{ rs.number }} of {{ rs.paginator.num_pages }}.</a>
					</li>
					{% if rs.has_next %}
					<li>
						<a href="?p={{ rs.next_page_number }}">next</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}

<script type="text/javascript" src="/static/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.datepicker.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.position.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.tooltip.js"></script>
<script type="text/javascript" src="/static/js/jock-citypicker-2.0.js"></script>

<script type="text/javascript">
	$(function() {

		$("#id_start").datepicker({
			dateFormat : 'yy-mm-dd'
		});

		//$("#id_end").datepicker({dateFormat: 'yy-mm-dd'});

		var c = document.getElementById("id_city");

		var fn2 = function(city) {
			c.value = city;
		};
		c.onclick = function() {
			citypicker.show({
				left : 300,
				top : 300,
				selected : fn2
			});
		};
		function hide_this() {
			if ($("#id_I_or_D").children('option:selected').val() == '0') {
				$("#id_sort_by").val(0);
				$("#id_sort_by").attr("hidden", true);
				$("[for ='id_sort_by']").attr('hidden', true);
			} else {
				$("#id_sort_by").attr("hidden", false);
				$("[for ='id_sort_by']").attr('hidden', false);
			}
		}

		hide_this();
		$("#id_I_or_D").change(function() {
			hide_this();
		});
	}); 
</script>
{% endblock %}